# main text of home
name: Oslo Software Architecture
bio: Det største arkitekturmiljøet i Norge
description: The homepage of OSWA.

url: https://github.com/OsloSWA # is overridden in _dev.yml and oswa_no.yml
timezone: Europe/Oslo

permalink: /:title/
markdown: kramdown
highlighter: rouge

title: Oslo Software Architecture
email: styret@oswa.no

# Social Media accounts
# facebook: myfacebook
twitter: OsloSWA
#instagram: OsloSWA
# pinterest: OsloSWA
# linkedin: OsloSWA
# youtube: OsloSWA
# spotify: OsloSWA
github: OsloSWA
# lanyrd: OsloSWA
# stackoverflow: 00000/OsloSWA
# medium: OsloSWA
# vimeo: OsloSWA

plugins_dir: ./_plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

collections:
  sections:
    output: false
  pages:
    output: true
    permalink: /:name.html

# Exclude from processing.
exclude:
  - package.json
  - package-lock.json
  - package-scripts.js
  - generator.js
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

destination: docs

sass:
  sass_dir: _sass
  style: :compressed
